name: Frontend CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    
    permissions:
     id-token: write # Required for OIDC
     contents: read  # Default for accessing repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::120569638976:role/GitHubActionsRole_summafyapp
          aws-region: us-east-1
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: summafy-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .